# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7 ,3.8, 3.9]
    steps:
    - uses: actions/checkout@v1
    - name: Install Sundails
      run: |
        sudo apt-get update
        sudo apt install -y gfortran libblas-dev liblapack-dev git build-essential cmake python3-dev
        git clone -b v5.1.0 https://github.com/LLNL/sundials.git
        mkdir sundials/build && cd sundials/build && cmake -DLAPACK_ENABLE=ON ..
        make && sudo make install
        cd .. && cd ..
    - name: Install Python3 Dependencies.
      run: |
        python3 -m pip install scikits.odes
        python3 -m pip install flake8 pytest coverage mock pytest-cov==2.6.1
        python3 -m pip install -e .
    - name: Lint with flake8
      run: |
          flake8 BondGraphTools
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 895919e9413384a08a878a372ecad8e82ac0f6f80933e23cc36261e9986d27c0
        LD_LIBRARY_PATH: /usr/local/lib:$LD_LIBRARY_PATH
      with:
        coverageCommand: pytest --runslow --cov=BondGraphTools --cov-report=xml test
